[package]
name = "canvas-node"
version = "0.1.0"
authors = ["Canvas"]
build = "build.rs"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
structopt = "0.3.8"
hex-literal = "0.2.1"

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox", features = ["wasmtime"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox", features = ["wasmtime"] }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox", features = ["wasmtime"] }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }

# These dependencies are used for the node's RPCs
jsonrpc-core = "15.0.0"
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }

canvas-runtime = { version = "0.1.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "wasmtime-sandbox" }

[[bin]]
name = "canvas"
path = "src/main.rs"
